//
//  AhamoveStyleKit.h
//  Ahamove
//
//  Created by DuongNgo on 12/30/17.
//  Copyright (c) 2017 Ahamove. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface AhamoveStyleKit : NSObject

// Drawing Methods
+ (void)drawPumbWithOuterColor: (UIColor*)outerColor innerColor: (UIColor*)innerColor viewHeight: (CGFloat)viewHeight viewWidth: (CGFloat)viewWidth maxOuterSize: (CGFloat)maxOuterSize maxInnerSize: (CGFloat)maxInnerSize minInnerSize: (CGFloat)minInnerSize progress: (CGFloat)progress;

// Generated Images
+ (UIImage*)imageOfMapDestIconWithFrame: (CGRect)frame pin_color: (UIColor*)pin_color text_color: (UIColor*)text_color number: (NSString*)number fontSize: (CGFloat)fontSize;
+ (UIImage*)imageOfFromMarkerWithFrame: (CGRect)frame pin_color: (UIColor*)pin_color;
+ (UIImage*)imageOfDestMarkerWithFrame: (CGRect)frame pin_color: (UIColor*)pin_color;
+ (UIImage*)imageOfDistanceMarkerWithFrame: (CGRect)frame title: (NSString*)title fontSize: (CGFloat)fontSize;
+ (UIImage*)imageOfEtaMarkerWithFrame: (CGRect)frame title: (NSString*)title fontSize: (CGFloat)fontSize;

@end
